### ISSUE TITLE
Add no FSOA rot exlcuding magma tempest to #kerapac-solo

### ISSUE THREAD

**Issue by inferiumRS3** [pvme/pvme-guides#2855]
![image](https://user-images.githubusercontent.com/94665678/167229908-0f68801c-5730-4826-b3d7-9bac7491e0d7.png)

**Comment by F1shBones** [comment]
After checking the rot and the CD between each corruption blast, it looks like replacing all magmas with it would be the best alternative without compromising the rot consistency. Would also make it easier to edit since we could simply add a "(replace with <:corruptblast:513190159194259467> if not owned)" on the Note

**Comment by Ferroric** [comment]
Small issue with that would be that magma works weird and the timing of the auto following is different.  There are 2 instances where this is an issue.  Would run it through senie if you wanted to implement that
