### ISSUE TITLE
Arrows explination

### ISSUE THREAD

**Issue by Ferroric** [pvme/pvme-guides#3599]
![image](https://user-images.githubusercontent.com/104602266/187812422-2cedd089-3738-4265-9384-ebf7bdcbc4c6.png)
Find somewhere to add this to prove the haters wrong

**Comment by Archken** [comment]
cant make it into a command since no good aliases are free, also that "b2b spec" point seems pretty ehhhhh to completely scrap bows for.

The only place it would really "fit" is dpm-advice-ranged, but even then its kinda irrelevant? Like end of the day all this is saying is arrows > bolts, which !ammo already does.

Like it gives "reasons" but they arent really "reasons", its just listing the effect and saying "believe me, this makes it better" which is just the same as saying "arrows > bolts"
